{
 "title": "API metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "App", "query": { "query": "label_values(app_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Request in progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(starlette_requests_in_progress{app_name=~\"$App\"}) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(starlette_request_duration_seconds_bucket{app_name=~\"$App\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Results",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(starlette_requests_total{app_name=~\"$App\"}) by (status_code, method))",
     "legendFormat": "{{method}}:{{status_code}}"
    }
   ]
  }
 ]
}